namespace FilmIzlemeUygulamasi
{
    partial class MovieAddForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MovieAddForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.lblTitle = new System.Windows.Forms.Label();
            this.txtTitle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtYear = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtRating = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSummary = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cmbCategory = new System.Windows.Forms.ComboBox();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnClose = new Bunifu.UI.WinForms.BunifuImageButton();
            this.lblCategory = new System.Windows.Forms.Label();
            this.btnManageCategory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pbPoster = new System.Windows.Forms.PictureBox();
            this.btnBrowsePoster = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblPosterPath = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.pbPoster)).BeginInit();
            this.SuspendLayout();
            
            // bunifuElipse1
            
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
           
            // lblTitle
            
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Location = new System.Drawing.Point(67, 25);
            this.lblTitle.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(467, 49);
            this.lblTitle.TabIndex = 11;
            this.lblTitle.Text = "ADD NEW MOVIE";
            this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            
            // txtTitle
           
            this.txtTitle.AcceptsReturn = false;
            this.txtTitle.AcceptsTab = false;
            this.txtTitle.AnimationSpeed = 200;
            this.txtTitle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTitle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTitle.AutoSizeHeight = true;
            this.txtTitle.BackColor = System.Drawing.Color.Transparent;
            this.txtTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTitle.BackgroundImage")));
            this.txtTitle.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTitle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTitle.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTitle.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTitle.BorderRadius = 1;
            this.txtTitle.BorderThickness = 1;
            this.txtTitle.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTitle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTitle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTitle.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTitle.DefaultText = "";
            this.txtTitle.FillColor = System.Drawing.Color.White;
            this.txtTitle.HideSelection = true;
            this.txtTitle.IconLeft = null;
            this.txtTitle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTitle.IconPadding = 10;
            this.txtTitle.IconRight = null;
            this.txtTitle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTitle.Lines = new string[0];
            this.txtTitle.Location = new System.Drawing.Point(67, 98);
            this.txtTitle.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtTitle.MaxLength = 32767;
            this.txtTitle.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTitle.Modified = false;
            this.txtTitle.Multiline = false;
            this.txtTitle.Name = "txtTitle";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTitle.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTitle.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTitle.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTitle.OnIdleState = stateProperties16;
            this.txtTitle.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtTitle.PasswordChar = '\0';
            this.txtTitle.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTitle.PlaceholderText = "Title";
            this.txtTitle.ReadOnly = false;
            this.txtTitle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTitle.SelectedText = "";
            this.txtTitle.SelectionLength = 0;
            this.txtTitle.SelectionStart = 0;
            this.txtTitle.ShortcutsEnabled = true;
            this.txtTitle.Size = new System.Drawing.Size(533, 49);
            this.txtTitle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTitle.TabIndex = 0;
            this.txtTitle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTitle.TextMarginBottom = 0;
            this.txtTitle.TextMarginLeft = 3;
            this.txtTitle.TextMarginTop = 1;
            this.txtTitle.TextPlaceholder = "Title";
            this.txtTitle.UseSystemPasswordChar = false;
            this.txtTitle.WordWrap = true;
            
            // txtYear
            
            this.txtYear.AcceptsReturn = false;
            this.txtYear.AcceptsTab = false;
            this.txtYear.AnimationSpeed = 200;
            this.txtYear.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtYear.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtYear.AutoSizeHeight = true;
            this.txtYear.BackColor = System.Drawing.Color.Transparent;
            this.txtYear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtYear.BackgroundImage")));
            this.txtYear.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtYear.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtYear.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtYear.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtYear.BorderRadius = 1;
            this.txtYear.BorderThickness = 1;
            this.txtYear.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtYear.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtYear.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtYear.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtYear.DefaultText = "";
            this.txtYear.FillColor = System.Drawing.Color.White;
            this.txtYear.HideSelection = true;
            this.txtYear.IconLeft = null;
            this.txtYear.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtYear.IconPadding = 10;
            this.txtYear.IconRight = null;
            this.txtYear.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtYear.Lines = new string[0];
            this.txtYear.Location = new System.Drawing.Point(67, 172);
            this.txtYear.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtYear.MaxLength = 32767;
            this.txtYear.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtYear.Modified = false;
            this.txtYear.Multiline = false;
            this.txtYear.Name = "txtYear";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtYear.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtYear.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtYear.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtYear.OnIdleState = stateProperties12;
            this.txtYear.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtYear.PasswordChar = '\0';
            this.txtYear.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtYear.PlaceholderText = "Release Year (e.g., 2024)";
            this.txtYear.ReadOnly = false;
            this.txtYear.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtYear.SelectedText = "";
            this.txtYear.SelectionLength = 0;
            this.txtYear.SelectionStart = 0;
            this.txtYear.ShortcutsEnabled = true;
            this.txtYear.Size = new System.Drawing.Size(253, 49);
            this.txtYear.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtYear.TabIndex = 1;
            this.txtYear.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtYear.TextMarginBottom = 0;
            this.txtYear.TextMarginLeft = 3;
            this.txtYear.TextMarginTop = 1;
            this.txtYear.TextPlaceholder = "Release Year (e.g., 2024)";
            this.txtYear.UseSystemPasswordChar = false;
            this.txtYear.WordWrap = true;
             
            // txtRating
           
            this.txtRating.AcceptsReturn = false;
            this.txtRating.AcceptsTab = false;
            this.txtRating.AnimationSpeed = 200;
            this.txtRating.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRating.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRating.AutoSizeHeight = true;
            this.txtRating.BackColor = System.Drawing.Color.Transparent;
            this.txtRating.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRating.BackgroundImage")));
            this.txtRating.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtRating.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRating.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtRating.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtRating.BorderRadius = 1;
            this.txtRating.BorderThickness = 1;
            this.txtRating.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtRating.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRating.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRating.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtRating.DefaultText = "";
            this.txtRating.FillColor = System.Drawing.Color.White;
            this.txtRating.HideSelection = true;
            this.txtRating.IconLeft = null;
            this.txtRating.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRating.IconPadding = 10;
            this.txtRating.IconRight = null;
            this.txtRating.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRating.Lines = new string[0];
            this.txtRating.Location = new System.Drawing.Point(347, 172);
            this.txtRating.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtRating.MaxLength = 32767;
            this.txtRating.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRating.Modified = false;
            this.txtRating.Multiline = false;
            this.txtRating.Name = "txtRating";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRating.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRating.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRating.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRating.OnIdleState = stateProperties8;
            this.txtRating.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtRating.PasswordChar = '\0';
            this.txtRating.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtRating.PlaceholderText = "Rating (e.g., 8.5)";
            this.txtRating.ReadOnly = false;
            this.txtRating.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRating.SelectedText = "";
            this.txtRating.SelectionLength = 0;
            this.txtRating.SelectionStart = 0;
            this.txtRating.ShortcutsEnabled = true;
            this.txtRating.Size = new System.Drawing.Size(253, 49);
            this.txtRating.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRating.TabIndex = 2;
            this.txtRating.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRating.TextMarginBottom = 0;
            this.txtRating.TextMarginLeft = 3;
            this.txtRating.TextMarginTop = 1;
            this.txtRating.TextPlaceholder = "Rating (e.g., 8.5)";
            this.txtRating.UseSystemPasswordChar = false;
            this.txtRating.WordWrap = true;
            
            // txtSummary
            
            this.txtSummary.AcceptsReturn = true;
            this.txtSummary.AcceptsTab = false;
            this.txtSummary.AnimationSpeed = 200;
            this.txtSummary.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSummary.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSummary.AutoSizeHeight = true;
            this.txtSummary.BackColor = System.Drawing.Color.Transparent;
            this.txtSummary.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSummary.BackgroundImage")));
            this.txtSummary.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSummary.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSummary.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSummary.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSummary.BorderRadius = 1;
            this.txtSummary.BorderThickness = 1;
            this.txtSummary.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSummary.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSummary.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSummary.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSummary.DefaultText = "";
            this.txtSummary.FillColor = System.Drawing.Color.White;
            this.txtSummary.HideSelection = true;
            this.txtSummary.IconLeft = null;
            this.txtSummary.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSummary.IconPadding = 10;
            this.txtSummary.IconRight = null;
            this.txtSummary.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSummary.Lines = new string[0];
            this.txtSummary.Location = new System.Drawing.Point(67, 332);
            this.txtSummary.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtSummary.MaxLength = 32767;
            this.txtSummary.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSummary.Modified = false;
            this.txtSummary.Multiline = false;
            this.txtSummary.Name = "txtSummary";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSummary.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSummary.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSummary.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSummary.OnIdleState = stateProperties4;
            this.txtSummary.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtSummary.PasswordChar = '\0';
            this.txtSummary.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSummary.PlaceholderText = "Summary / Synopsis";
            this.txtSummary.ReadOnly = false;
            this.txtSummary.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSummary.SelectedText = "";
            this.txtSummary.SelectionLength = 0;
            this.txtSummary.SelectionStart = 0;
            this.txtSummary.ShortcutsEnabled = true;
            this.txtSummary.Size = new System.Drawing.Size(533, 185);
            this.txtSummary.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSummary.TabIndex = 5;
            this.txtSummary.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSummary.TextMarginBottom = 0;
            this.txtSummary.TextMarginLeft = 3;
            this.txtSummary.TextMarginTop = 1;
            this.txtSummary.TextPlaceholder = "Summary / Synopsis";
            this.txtSummary.UseSystemPasswordChar = false;
            this.txtSummary.WordWrap = true;
           
            // cmbCategory
            
            this.cmbCategory.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCategory.Location = new System.Drawing.Point(67, 271);
            this.cmbCategory.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.cmbCategory.Name = "cmbCategory";
            this.cmbCategory.Size = new System.Drawing.Size(399, 24);
            this.cmbCategory.TabIndex = 3;
            
            // btnSave
           
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "SAVE MOVIE";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges3;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSave.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeft = null;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRight = null;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSave.IdleBorderRadius = 0;
            this.btnSave.IdleBorderThickness = 0;
            this.btnSave.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(67, 542);
            this.btnSave.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 1;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 1;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.BorderRadius = 1;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 1;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(533, 55);
            this.btnSave.TabIndex = 6;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            
            // btnClose
             
            this.btnClose.ActiveImage = null;
            this.btnClose.AllowAnimations = true;
            this.btnClose.AllowBuffering = false;
            this.btnClose.AllowToggling = false;
            this.btnClose.AllowZooming = true;
            this.btnClose.AllowZoomingOnFocus = false;
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnClose.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnClose.ErrorImage")));
            this.btnClose.FadeWhenInactive = false;
            this.btnClose.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnClose.Image = ((System.Drawing.Image)(resources.GetObject("btnClose.Image")));
            
            this.btnClose.ImageLocation = null;
            this.btnClose.ImageMargin = 20;
            this.btnClose.ImageSize = new System.Drawing.Size(31, 30);
            this.btnClose.ImageZoomSize = new System.Drawing.Size(51, 50);
            this.btnClose.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnClose.InitialImage")));
            this.btnClose.Location = new System.Drawing.Point(880, 4);
            this.btnClose.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnClose.Name = "btnClose";
            this.btnClose.Rotation = 0;
            this.btnClose.ShowActiveImage = true;
            this.btnClose.ShowCursorChanges = true;
            this.btnClose.ShowImageBorders = true;
            this.btnClose.ShowSizeMarkers = false;
            this.btnClose.Size = new System.Drawing.Size(51, 50);
            this.btnClose.TabIndex = 9;
            this.btnClose.ToolTipText = "";
            this.btnClose.WaitOnLoad = false;
            
            this.btnClose.ZoomSpeed = 10;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            
            // lblCategory
            
            this.lblCategory.AutoSize = true;
            this.lblCategory.ForeColor = System.Drawing.Color.Silver;
            this.lblCategory.Location = new System.Drawing.Point(67, 246);
            this.lblCategory.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblCategory.Name = "lblCategory";
            this.lblCategory.Size = new System.Drawing.Size(65, 16);
            this.lblCategory.TabIndex = 10;
            this.lblCategory.Text = "Category:";
            
            // btnManageCategory
           
            this.btnManageCategory.AllowAnimations = true;
            this.btnManageCategory.AllowMouseEffects = true;
            this.btnManageCategory.AllowToggling = false;
            this.btnManageCategory.AnimationSpeed = 200;
            this.btnManageCategory.AutoGenerateColors = false;
            this.btnManageCategory.AutoRoundBorders = false;
            this.btnManageCategory.AutoSizeLeftIcon = true;
            this.btnManageCategory.AutoSizeRightIcon = true;
            this.btnManageCategory.BackColor = System.Drawing.Color.Transparent;
            this.btnManageCategory.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnManageCategory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnManageCategory.BackgroundImage")));
            this.btnManageCategory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageCategory.ButtonText = "Manage";
            this.btnManageCategory.ButtonTextMarginLeft = 0;
            this.btnManageCategory.ColorContrastOnClick = 45;
            this.btnManageCategory.ColorContrastOnHover = 45;
            this.btnManageCategory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnManageCategory.CustomizableEdges = borderEdges2;
            this.btnManageCategory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnManageCategory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageCategory.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnManageCategory.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnManageCategory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnManageCategory.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnManageCategory.ForeColor = System.Drawing.Color.White;
            this.btnManageCategory.IconLeft = null;
            this.btnManageCategory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageCategory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageCategory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnManageCategory.IconMarginLeft = 11;
            this.btnManageCategory.IconPadding = 10;
            this.btnManageCategory.IconRight = null;
            this.btnManageCategory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageCategory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageCategory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnManageCategory.IconSize = 25;
            this.btnManageCategory.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnManageCategory.IdleBorderRadius = 0;
            this.btnManageCategory.IdleBorderThickness = 0;
            this.btnManageCategory.IdleFillColor = System.Drawing.Color.Empty;
            this.btnManageCategory.IdleIconLeftImage = null;
            this.btnManageCategory.IdleIconRightImage = null;
            this.btnManageCategory.IndicateFocus = false;
            this.btnManageCategory.Location = new System.Drawing.Point(480, 271);
            this.btnManageCategory.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnManageCategory.Name = "btnManageCategory";
            this.btnManageCategory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageCategory.OnDisabledState.BorderRadius = 1;
            this.btnManageCategory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageCategory.OnDisabledState.BorderThickness = 1;
            this.btnManageCategory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageCategory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageCategory.OnDisabledState.IconLeftImage = null;
            this.btnManageCategory.OnDisabledState.IconRightImage = null;
            this.btnManageCategory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnManageCategory.onHoverState.BorderRadius = 1;
            this.btnManageCategory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageCategory.onHoverState.BorderThickness = 1;
            this.btnManageCategory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnManageCategory.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnManageCategory.onHoverState.IconLeftImage = null;
            this.btnManageCategory.onHoverState.IconRightImage = null;
            this.btnManageCategory.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageCategory.OnIdleState.BorderRadius = 1;
            this.btnManageCategory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageCategory.OnIdleState.BorderThickness = 1;
            this.btnManageCategory.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageCategory.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnManageCategory.OnIdleState.IconLeftImage = null;
            this.btnManageCategory.OnIdleState.IconRightImage = null;
            this.btnManageCategory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageCategory.OnPressedState.BorderRadius = 1;
            this.btnManageCategory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageCategory.OnPressedState.BorderThickness = 1;
            this.btnManageCategory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageCategory.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnManageCategory.OnPressedState.IconLeftImage = null;
            this.btnManageCategory.OnPressedState.IconRightImage = null;
            this.btnManageCategory.Size = new System.Drawing.Size(120, 31);
            this.btnManageCategory.TabIndex = 4;
            this.btnManageCategory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnManageCategory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnManageCategory.TextMarginLeft = 0;
            this.btnManageCategory.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnManageCategory.UseDefaultRadiusAndThickness = true;
            this.btnManageCategory.Click += new System.EventHandler(this.btnManageCategory_Click);
            
            // pbPoster
          
            this.pbPoster.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.pbPoster.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pbPoster.Location = new System.Drawing.Point(640, 98);
            this.pbPoster.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.pbPoster.Name = "pbPoster";
            this.pbPoster.Size = new System.Drawing.Size(226, 295);
            this.pbPoster.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pbPoster.TabIndex = 7;
            this.pbPoster.TabStop = false;
           
            // btnBrowsePoster
           
            this.btnBrowsePoster.AllowAnimations = true;
            this.btnBrowsePoster.AllowMouseEffects = true;
            this.btnBrowsePoster.AllowToggling = false;
            this.btnBrowsePoster.AnimationSpeed = 200;
            this.btnBrowsePoster.AutoGenerateColors = false;
            this.btnBrowsePoster.AutoRoundBorders = false;
            this.btnBrowsePoster.AutoSizeLeftIcon = true;
            this.btnBrowsePoster.AutoSizeRightIcon = true;
            this.btnBrowsePoster.BackColor = System.Drawing.Color.Transparent;
            this.btnBrowsePoster.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnBrowsePoster.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBrowsePoster.BackgroundImage")));
            this.btnBrowsePoster.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowsePoster.ButtonText = "Browse Poster";
            this.btnBrowsePoster.ButtonTextMarginLeft = 0;
            this.btnBrowsePoster.ColorContrastOnClick = 45;
            this.btnBrowsePoster.ColorContrastOnHover = 45;
            this.btnBrowsePoster.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnBrowsePoster.CustomizableEdges = borderEdges1;
            this.btnBrowsePoster.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBrowsePoster.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBrowsePoster.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnBrowsePoster.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnBrowsePoster.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBrowsePoster.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnBrowsePoster.ForeColor = System.Drawing.Color.White;
            this.btnBrowsePoster.IconLeft = null;
            this.btnBrowsePoster.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBrowsePoster.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBrowsePoster.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBrowsePoster.IconMarginLeft = 11;
            this.btnBrowsePoster.IconPadding = 10;
            this.btnBrowsePoster.IconRight = null;
            this.btnBrowsePoster.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBrowsePoster.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBrowsePoster.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBrowsePoster.IconSize = 25;
            this.btnBrowsePoster.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnBrowsePoster.IdleBorderRadius = 0;
            this.btnBrowsePoster.IdleBorderThickness = 0;
            this.btnBrowsePoster.IdleFillColor = System.Drawing.Color.Empty;
            this.btnBrowsePoster.IdleIconLeftImage = null;
            this.btnBrowsePoster.IdleIconRightImage = null;
            this.btnBrowsePoster.IndicateFocus = false;
            this.btnBrowsePoster.Location = new System.Drawing.Point(640, 406);
            this.btnBrowsePoster.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnBrowsePoster.Name = "btnBrowsePoster";
            this.btnBrowsePoster.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBrowsePoster.OnDisabledState.BorderRadius = 1;
            this.btnBrowsePoster.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowsePoster.OnDisabledState.BorderThickness = 1;
            this.btnBrowsePoster.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBrowsePoster.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBrowsePoster.OnDisabledState.IconLeftImage = null;
            this.btnBrowsePoster.OnDisabledState.IconRightImage = null;
            this.btnBrowsePoster.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnBrowsePoster.onHoverState.BorderRadius = 1;
            this.btnBrowsePoster.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowsePoster.onHoverState.BorderThickness = 1;
            this.btnBrowsePoster.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnBrowsePoster.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBrowsePoster.onHoverState.IconLeftImage = null;
            this.btnBrowsePoster.onHoverState.IconRightImage = null;
            this.btnBrowsePoster.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnBrowsePoster.OnIdleState.BorderRadius = 1;
            this.btnBrowsePoster.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowsePoster.OnIdleState.BorderThickness = 1;
            this.btnBrowsePoster.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnBrowsePoster.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBrowsePoster.OnIdleState.IconLeftImage = null;
            this.btnBrowsePoster.OnIdleState.IconRightImage = null;
            this.btnBrowsePoster.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBrowsePoster.OnPressedState.BorderRadius = 1;
            this.btnBrowsePoster.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBrowsePoster.OnPressedState.BorderThickness = 1;
            this.btnBrowsePoster.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBrowsePoster.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBrowsePoster.OnPressedState.IconLeftImage = null;
            this.btnBrowsePoster.OnPressedState.IconRightImage = null;
            this.btnBrowsePoster.Size = new System.Drawing.Size(227, 49);
            this.btnBrowsePoster.TabIndex = 8;
            this.btnBrowsePoster.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBrowsePoster.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBrowsePoster.TextMarginLeft = 0;
            this.btnBrowsePoster.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBrowsePoster.UseDefaultRadiusAndThickness = true;
            this.btnBrowsePoster.Click += new System.EventHandler(this.btnBrowsePoster_Click);
           
            // lblPosterPath
            
            this.lblPosterPath.AutoSize = true;
            this.lblPosterPath.Location = new System.Drawing.Point(640, 62);
            this.lblPosterPath.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.lblPosterPath.Name = "lblPosterPath";
            this.lblPosterPath.Size = new System.Drawing.Size(0, 16);
            this.lblPosterPath.TabIndex = 0;
            this.lblPosterPath.Visible = false;
             
            // MovieAddForm
            
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(34)))), ((int)(((byte)(34)))));
            this.ClientSize = new System.Drawing.Size(933, 615);
            this.Controls.Add(this.lblPosterPath);
            this.Controls.Add(this.btnBrowsePoster);
            this.Controls.Add(this.pbPoster);
            this.Controls.Add(this.btnManageCategory);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.txtSummary);
            this.Controls.Add(this.cmbCategory);
            this.Controls.Add(this.lblCategory);
            this.Controls.Add(this.txtRating);
            this.Controls.Add(this.txtYear);
            this.Controls.Add(this.txtTitle);
            this.Controls.Add(this.lblTitle);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "MovieAddForm";
            this.Text = "MovieAddForm";
            this.Load += new System.EventHandler(this.MovieAddForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pbPoster)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

       

        // Private Tanımlar
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.Label lblTitle;
        private Bunifu.UI.WinForms.BunifuTextBox txtTitle;
        private Bunifu.UI.WinForms.BunifuTextBox txtYear;
        private Bunifu.UI.WinForms.BunifuTextBox txtRating;
        private Bunifu.UI.WinForms.BunifuTextBox txtSummary;
        private System.Windows.Forms.ComboBox cmbCategory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuImageButton btnClose;
        private System.Windows.Forms.Label lblCategory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnManageCategory;
        private System.Windows.Forms.PictureBox pbPoster; // YENİ
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBrowsePoster; // YENİ
        private System.Windows.Forms.Label lblPosterPath; // YENİ
    }
}